CREATE TYPE "quote_status" AS ENUM ('open', 'converted', 'cancelled');

CREATE TABLE IF NOT EXISTS "quotes" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "quote_number" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "status" "quote_status" DEFAULT 'open' NOT NULL,
  "warehouse_id" uuid NOT NULL REFERENCES "warehouses"("id"),
  "customer_name" text,
  "customer_email" text,
  "customer_phone" text,
  "customer_address" text,
  "customer_id_number" text,
  "total_price" numeric(10, 2),
  "currency" text DEFAULT 'ILS' NOT NULL,
  "notes" text,
  "quote_date" timestamptz DEFAULT now() NOT NULL,
  "created_by" uuid REFERENCES "users"("id"),
  "converted_sale_id" uuid REFERENCES "sales"("id"),
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "quotes_quote_number_idx" ON "quotes" ("quote_number");
CREATE INDEX IF NOT EXISTS "quotes_status_idx" ON "quotes" ("status");
CREATE INDEX IF NOT EXISTS "quotes_warehouse_id_idx" ON "quotes" ("warehouse_id");

CREATE TABLE IF NOT EXISTS "quote_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "quote_id" uuid NOT NULL REFERENCES "quotes"("id") ON DELETE CASCADE,
  "product_id" uuid REFERENCES "products"("id"),
  "sku" text NOT NULL,
  "name" text NOT NULL,
  "quantity" integer NOT NULL,
  "unit_price" numeric(10, 2),
  "line_total" numeric(10, 2)
);

CREATE INDEX IF NOT EXISTS "quote_items_quote_id_idx" ON "quote_items" ("quote_id");
